apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}-deployment
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: bookapp
    spec:
      containers:
      - name:  bookapp
        image: spectro30/bookapp:latest
        ports:
        - containerPort: 8888